### DISCUSSION TITLE
Run Martin on subpath with Traefik proxy

### DISCUSSION THREAD

**Discussion by justb4** [maplibre/martin#1184] [Ideas]
Hopefully this is more a question than a feature request: I am trying to integrate Martin using Docker (Compose) with a [Traefik](https://doc.traefik.io/traefik/) proxy front-end. From the documentation I understand [how this is realised with Nginx](https://maplibre.org/martin/run-with-nginx.html)  but somehow I can't get this scenario to work with Traefik. Connection to DB is ok. Problem: the returned TileJSON contains the external host+port but not the sub-path. This image should make the problem somewhat clearer:

![image](https://github.com/maplibre/martin/assets/582630/0721f75e-6f7b-450e-9686-2b8646cba0c9)

Traefik runs here at `http://localhost:8000` (or in production on HTTPS, Martin in Docker Container on `0.0.0.0:3000`). So the external `protocol://host:port` is handled ok. Here the subpath is `/vt`. As you can see in the TileJSON, that subpath is not present. This is a recurring problem with proxied services. For example in Python Flask apps one can set an env var `SCRIPT_NAME`, and there are many other 'tricks' or mostly config settings like `BasePath`, but via HTTP Headers is more elegant. 

In the Nginx setup it looks like a HTTP Header `X-Rewrite-URL` does the trick, but can't find an equivalent setting for Traefik. As Traefik is a widely used frontend, IMHO it is useful to figure out, maybe even extend the Martin config, or at least extend the docs how to setup with Traefik.

My Docker Compose file is like (with some env vars like `SERVICE_NAME=martin`), so the prefix path to the `martin` container is `/vt`, which is stripped before forwarding to the martin Container:

```
version: "3"

services:

  martin:
    image: ghcr.io/maplibre/martin:v0.13.0
    container_name: martin
.
.
    environment:
      - DATABASE_URL=postgresql://${PG_USER}:${PG_PASSWORD}@....
      - RUST_LOG=debug

    labels:
      # Enable Traefik routing on overlay service network
      - "traefik.enable=true"
      - "traefik.docker.network=service-network"
      # strip prefix
      - "traefik.http.middlewares.martin-stripprefix.stripprefix.prefixes=/vt"

      # Define local http router
      - "traefik.http.routers.${SERVICE_NAME}_http.rule=Host(`localhost`) && PathPrefix(`/vt`)"
      - "traefik.http.routers.${SERVICE_NAME}_http.entrypoints=http"
      - "traefik.http.routers.${SERVICE_NAME}_http.middlewares=martin-stripprefix@docker"

      # Define SSL/https router
      - "traefik.http.routers.${SERVICE_NAME}_https.rule=Host(`${TRAEFIK_SSL_DOMAIN}`) && PathPrefix(`/vt`)"
      - "traefik.http.routers.${SERVICE_NAME}_https.entrypoints=https"
      - "traefik.http.routers.${SERVICE_NAME}_https.tls=${TRAEFIK_USE_TLS}"
      - "traefik.http.routers.${SERVICE_NAME}_https.tls.certresolver=${TRAEFIK_SSL_CERT_RESOLVER}"
      - "traefik.http.routers.${SERVICE_NAME}_https.tls.options=my_default@file"
      - "traefik.http.routers.${SERVICE_NAME}_https.middlewares=secure-headers@file,martin-stripprefix@docker"
.
.
```
