### DISCUSSION TITLE
mbtiles file serving using Compose

### DISCUSSION THREAD

**Discussion by BigBoulard** [maplibre/martin#1237] [Q&A] [answered]
Hi Team,

I've generated a `belgium.mbtiles` file to be served by `martin`.
I know that the bind mount works, I tried the below config but I get `Unrecognizable connection strings: ["/mbfiles/belgium.mbtiles"]`

```yaml
martin:
    image: ghcr.io/maplibre/martin:v0.13.0
    ports:
      - 3000:3000
    environment:
      - RUST_LOG=debug
    volumes:
      - ../docker/volumes/martin/config.yaml:/config/config.yaml
      - ../docker/volumes/martin/belgium.mbtiles:/belgium.mbtiles
    command: /mbfiles/belgium.mbtiles # ???
```

I tried another approach by adding another port mapping in `compose`,  logging into the instance, and executing `martin /belgium.mbtiles -l 3001` but I get `Unable to bind to 3001: invalid socket address`.

**Comment by BigBoulard** [comment]
We can't pass a `config.yaml` file and feed `martin` with a `mbtiles` file **at the same time**.
We must pass the options to the command line to serve a `.mbtiles` file,  generate a sprite, and use some fonts.

On top of that, we can still specify a database URL ... I don't know what it's doing yet but it's possible.

```yaml
martin:
    image: ghcr.io/maplibre/martin:v0.13.0
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://martin_pguser:${MARTIN_PGPASSWORD}@postgres/osmdb
      - RUST_LOG=debug
    volumes:
      - ../docker/volumes/martin/fonts:/fonts
      - ../docker/volumes/martin/icons:/sprite
      - ../docker/volumes/martin/belgium.mbtiles:/belgium.mbtiles
    command:/belgium.mbtiles --sprite /sprite --font /fonts
```

Then if we hit `0.0.0.0:3000/catalog` we see a new endpoint:

```json
{
  "tiles": {
    "belgium": { <---- HERE
      "content_type": "application/x-protobuf",
      "content_encoding": "gzip",
      "name": "planet_osm_point,planet_osm_line,planet_osm_roads,planet_osm_polygon",
      "description": "public.planet_osm_point.way\npublic.planet_osm_line.way\npublic.planet_osm_roads.way\npublic.planet_osm_polygon.way"
    },
    "planet_osm_line": {
      "content_type": "application/x-protobuf",
      "description": "public.planet_osm_line.way"
    },
    "planet_osm_point": {
      "content_type": "application/x-protobuf",
      "description": "public.planet_osm_point.way"
    },
    "planet_osm_polygon": {
      "content_type": "application/x-protobuf",
      "description": "public.planet_osm_polygon.way"
    },
    "planet_osm_roads": {
      "content_type": "application/x-protobuf",
      "description": "public.planet_osm_roads.way"
    }
  },
  "sprites": {
    "sprite": {
      "images": [] // 101 items
    }
  },
  "fonts": {
    "Noto Sans Bold": {},
    "Noto Sans Italic": {},
    "Noto Sans Light": {},
    "Noto Sans Regular": {}
  }
}


```
