### DISCUSSION TITLE
How to serve another vector_layer in tilejson?

### DISCUSSION THREAD

**Discussion by zmatez** [maplibre/martin#1560] [General]
I'm trying to put centered labels in Maplibre on geometries, but to do it I need to calculate center points. So to my PostGIS table I've added:
```sql
ALTER TABLE maps.terrain_wojewodztwa ADD COLUMN centroid GEOMETRY(Point, 4326);
UPDATE maps.terrain_wojewodztwa
SET centroid = ST_Centroid(geom);
CREATE INDEX idx_terrain_wojewodztwa_centroid ON maps.terrain_wojewodztwa USING GIST (centroid);
```  
but on that table (with both geom and centroid) it says  `Unable to configure source terrain_wojewodztwa because property 'centroid' was not found`.  Config looks like:
```yaml
    terrain_wojewodztwa:
      layer_id: terrain_wojewodztwa
      schema: maps
      table: terrain_wojewodztwa
      srid: 4326
      geometry_column: geom
      properties:
        gid: Integer
        jpt_nazwa_: String
        centroid: Point
```
so sounds like it can't serve two geometries (multipolygon and point) at once - **so how could I serve this as one endpoint**, but in TileJSON it'd give me **both geometry and centroid in separate vector_layers**:
```json
"vector_layers": [
    {
      "id": "terrain_wojewodztwa",
      "fields": {
        "gid": "Integer",
        "jpt_nazwa_": "String"
      }
    },
    // here another layer just for centroid, with same gid and jpt_nazwa_
  ],
```
is it possible or **I have to create separate endpoint** like with different table or function to serve centroid separately? Thanks

**Comment by zmatez** [comment]
Alright so solved it like this:
```yaml
  tables:
    terrain_wojewodztwa_polygon:
      layer_id: terrain_wojewodztwa_polygon
      schema: maps
      table: terrain_wojewodztwa
      srid: 4326
      geometry_column: geom
      properties:
        gid: Integer
        jpt_nazwa_: String
    terrain_wojewodztwa_centroid:
      layer_id: terrain_wojewodztwa_centroid
      schema: maps
      table: terrain_wojewodztwa
      srid: 4326
      geometry_column: centroid
      properties:
        gid: Integer
        jpt_nazwa_: String
```
would be cool tho if those could have the same name, but it's alright to call `0.0.0.0:8000/terrain_wojewodztwa_polygon,terrain_wojewodztwa_centroid`
