### DISCUSSION TITLE
Proposed changes to URL and Config structure

### DISCUSSION THREAD

**Discussion by nyurik** [maplibre/martin#430] [Ideas]
I would like to propose a number changes to Martin:
* URL structure in order to make it more generic, as well as expose less internal data to the world
* Improve config file structure to allow multiple postgreSQL connections and other source types

### URL changes
* No `/rpc/<id>/...` paths. For backward support, we could do a redirect to `/<id>/...`
* Reconsider schema prefixes, e.g. "public." in `public.mytable`.
* Remove all suffixes, e.g. `.pbf`, `.json`, etc.

path|info
|---|---|
`/<id>/z/x/y` | Get a tile from the given source. The tile format is source-dependent.
`/<id>` | Get TileJSON description of the source
`/` | Get the index manifest -- a list of the available sources.<br><br>TODO: This endpoint may need to be reworked - we do not want to expose too much information about the internal configuration here.
`/health` | Returns a 200 `OK` simple text response

### URL source identifiers
* All source IDs must match a regex `[_a-z0-9]+` for simplicity. No commas or slashes.
    * We may allow more symbols like `-`, `_`, and `.`  -- having dots allow `public.mytable` style naming, which somewhat exposes internal postgreSQL detail, but this might be ok.
* An identifier must not be one of the reserved words like `index` or `rpc`
* It is guaranteed that someone will have multiple sources with the same ID, e.g. a table named the same as an .mbtiles file, etc.  We need to decide the resolution process.  Some ideas:
    * Introduce a `--on-id-conflict (stop | rename | ignore)` CLI/config setting that will control what Martin does in case of an ID
    * In case of the `rename` mode, add a counter at the end of an id, e.g. `tbl`, `tbl1`, `tbl2`, ...
    * In case of the `ignore` mode, some arbitrary source ID wins (possibly the latest one in the processing queue)

### Source auto-discovery
We want to have a simple no-configuration mode, so that developers can start using Martin with the least amount of pain:
* If `DATABASE_URL` env var is not set, and Martin started with no parameters, look in the current directory for the `*.mbtiles` files, and make them all available as sources
* PostgreSQL table autodiscovery can be controlled with a `discover_tables_as: (table | schema_table | schema_table_column)` config parameter. Depending on the setting, tables with geo columns will become `table`, `schema.table` or `schema.table.geo_column` sources.
* PostgreSQL functions autodiscovery can be controlled with a `discover_funcs_as: (func | schema_func)` config parameter. Depending on the setting, functions will become `func` or `schema.func` sources.

### Per-source Configuration
* Allow multiple data sources
* Do not allow duplicate IDs (or show a warning?)
* Document defaults

### Proposed Config Structure

```yaml
---
# Trust invalid certificates. This introduces significant vulnerabilities, and should only be used as a last resort.
danger_accept_invalid_certs: false
# Connection keep alive timeout [default: 75]
keep_alive: 75
# The socket address to bind [default: 127.0.0.1:3000]
listen_addresses: '0.0.0.0:3000'
# Number of web server workers
worker_processes: 8
# Allow users to discover available sources with a `GET /` [default: true] 
enable_sources_manifest: false
# Alias legacy /rpc/... requests to the root. This works for all sources, not just function calls. [default: false]
legacy_rpc_paths: true
# Allow the same source to be exposed as multiple IDs, or combine multiple sources into one
aliases:
  public.tbl1: tbl1
  composite1: tbl1,func1,tbl2
# In case multiple sources have the same ID during auto-discovery, this controls how they will be handled.
# Allowed values: "stop" - Martin exits, "ignore" - only one of the sources becomes available,
# and "rename" - generate unique source name automatically.
on_id_conflict: rename

# All .mbtiles file sources
# Each sub-key is a separate source ID
mbtiles:
  # If set, will automatically make all *.mbtiles files in this directory available as sources
  # The path is relative to the config file
  discover_files_in: ./
  # Map of source IDs -> mbtile file sources
  files:
    # Simple configuration with the value being the file path itself relative to the config file
    src1: path/to/file1.mbtiles
    # Customized configuration (actual fields are TBD)
    src2:
      file: path/to/file2.mbtiles
      format: jpeg

# One or several PostgreSQL sources
postgres:
  # Database connection string
  connection_string: 'postgres://postgres@localhost:5432/db'
  # If a spatial table has SRID 0, then this SRID will be used as a fallback
  default_srid: 4326
  # Maximum connections pool size [default: 20]
  pool_size: 20
  # Optionally limit the number of features a table source would return
  max_feature_count: 5000
  # If set to one of the valid values, automatically finds all tables and expose them as sources.
  # Valid values:  "table" - source ID is the table name,  "schema_table" - ID is "schema.table",
  # "schema_table_column" - source ID is "schema.table.geometry_column". 
  discover_tables_as: schema_table_column
  # If set to one of the valid values, automatically finds all MVT-generating functions and expose them as sources.
  # Valid values:  "func" - source ID is the name of the function,  "schema_func" - ID is "schema.func"
  discover_funcs_as: schema_table_column

  # Map of source IDs -> table sources
  tables:
    tbl1:
      # Table schema and name (required)
      schema: public
      table: my_table
      # Geometry SRID (optional)
      srid: 4326
      # Geometry column name (required)
      geom_column: geom
      # Feature id column name. If null (or missing), will not be set.
      id_column: null
      # An integer specifying the minimum zoom level
      minzoom: 0
      # An integer specifying the maximum zoom level. MUST be >= minzoom
      maxzoom: 30
      # The maximum extent of available map tiles. Bounds MUST define an area
      # covered by all zoom levels. The bounds are represented in WGS:84
      # latitude and longitude values, in the order left, bottom, right, top.
      # Values may be integers or floating point numbers.
      bounds: [-180.0, -90.0, 180.0, 90.0]
      # Tile extent in tile coordinate space
      extent: 4096
      # Buffer distance in tile coordinate space to optionally clip geometries
      buffer: 64
      # Boolean to control if geometries should be clipped or encoded as is
      clip_geom: true
      # Geometry type
      geom_type: GEOMETRY
      # Optionally limit the number of features a table source would return (overrides the one above)
      max_feature_count: 5000
      # List of columns, that should be encoded as tile properties. If not set, will be set automatically.
      properties:
        gid: int4

  # Map of source IDs -> function sources
  functions:
    func1:
      # Schema and function name (required)
      schema: public
      function: my_func
      # An integer specifying the minimum zoom level
      minzoom: 0
      # An integer specifying the maximum zoom level. MUST be >= minzoom
      maxzoom: 30
      # The maximum extent of available map tiles.
      bounds: [-180.0, -90.0, 180.0, 90.0]
```

**Comment by sharkAndshark** [comment]
The design of API and config above is simple and expressive. : D  
A few naive thoughts here.

## Feature count limit
Maybe it's an opportunity to resolve  #384 .How about give Optional global and inline options:feature_limit. Like:
```yml
server:
    ....
    feature_limit: 10000
    ....
sources:
    postgres:
        ....
        tables:
            tbl1:
                ....
                feature_limit:5000
                ....
```

## Duplicate id
A warning(and suggest user use aliases in config file?) and automatically rename duplicates like someDuplicate1,someDuplicate2..etc?
## Composite
|API | Features     | Config |
|---------------- | ------------- |------------- |
|  `/id1,id2/z/x/y.mvt` and `/id1,id2.json`   |   flexible |  |
|  `/compositeid1/z/x/y.mvt` and `/compositeid1.json` |  not flexible but back end can control everything|  restrict composites by something like below|
```yml
server:
  Composite:
    "compositeid1": tbl1,tbl2
    "compositeid2": tbl3,tbl4,
```
## Positoin of alias part
Maybe place alias part under pg if it is dedicated to pg?
