### DISCUSSION TITLE
How to set a specific configuration file on docker-compose

### DISCUSSION THREAD

**Discussion by dansku** [maplibre/martin#629] [Q&A]
Hello, 

I am trying to setup martin to run `martin.yaml` with docker compose but I can't figure out how to setup it, something along the lines:
 
```
  martin:
    image: maplibre/martin:v0.8.0
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://hotspotty:maptiles@db/maptiles
    volumes:
      - ./martin.yaml:/config.yaml
    depends_on:
      - db
```

Thank you

**Comment by stepankuzmin** [comment]
@dansku, could you please add more context? It's unclear to me what is the problem you are facing here.

**Comment by dansku** [comment]
hey @stepankuzmin sorry for that.

I have this docker-compose file:

```
version: '3'


services:

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./cache:/var/cache/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - martin

  martin:
    image: maplibre/martin:v0.8.0
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://temp:temp@db/temp
    volumes:
      - ./martin.yaml:/config.yaml
    depends_on:
      - db

  db:
    image: postgis/postgis:14-3.3-alpine
    restart: unless-stopped
    platform: linux/amd64
    environment:
      - POSTGRES_DB=temp
      - POSTGRES_USER=temp
      - POSTGRES_PASSWORD=temp
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  ```
  
When I was working without the docker-compose, I've setup a config.yaml file that I use to setup all the tables i want martin to run and all.

Now that I am setting it up with docker-compose, i don't see where to set the config file I want it to load when running the `docker-compose up` command.

Does it make more sense?

Thank you

**Reply by nyurik** [reply]
@dansku hi, did you figure out what was wrong?

**Reply by dansku** [reply]
@nyurik I did not, couldn't figure out how to load a custom config.yaml file when working with docker-compose.

**Reply by none00140** [reply]
Need to add command line or build from dockerfile.

FROM maplibre/martin
COPY config.yaml .
CMD ["--config", "config.yaml"]

**Comment by thormme** [comment]
You just need to pass the file you mounted via a volume as the `--config` parameter to the `command` option.
```
martin:
    image: maplibre/martin:v0.14.2
    restart: unless-stopped
    ports:
      - "3000:3000"
    command: --config /config.yaml
    volumes:
      - ./martin.yaml:/config.yaml
```
