### DISCUSSION TITLE
Specifying an `id` with `auto_publish` like `id_column`

### DISCUSSION THREAD

**Discussion by KiwiKilian** [maplibre/martin#680] [Ideas]
We are using Martin with the following config:
```yaml
postgres:
  connection_string: ${DATABASE_URL}
  auto_publish:
    from_schemas:
      - frontend
```

So everything in our `frontend` schema is published on restart.

What I'm missing is setting the `id` for those autopublished tables. I would either like to specify a column for all tables (just like `id_column` for specific tables) or Martin to automatically use a column named `id` and being of type `int`. I know I can use `promoteId` with `maplibre-gl-js` to specifiy my `id` property on the frontend as the MVT `id`, but it would feel more natural to properly publish from Martin.

**Comment by nyurik** [comment]
I guess we could add an `id_column` to the tables. My only concern is that `id_format` and `id_column` are talking about two different IDs... and technically we should have called the first as `source_id_format` (we could do a backward-compatible rename I guess).

```yaml
  auto_publish:
    tables:
      # Set a custom source ID based on the table name
      id_format: 'table.{schema}.{table}.{column}'
      # A table column to use as the feature ID
      # If a table has no column with this name, `id_column` will not be set for that table.
      # We could even allow a list of strings here - the first found column will be treated as a feature ID.
      id_column: 'id'
```
