### DISCUSSION TITLE
Serve tiles over https

### DISCUSSION THREAD

**Discussion by SamG92** [maplibre/martin#868] [Q&A]
Hello there,

Sorry for my naïve question ... 

I would like tiles to be served over https:
```
map.addSource('mydata', {
            type: 'vector',
            url: 'https://bdd.mydomain.com:1000/mutation',
            promoteId: 'idm'
        });
```

How do I configure Martin to do so? Do I need some additional webserver or any specific configuration ?

Here is my current config file (where I generated a letsencrypt certificate for my bdd.mydomain.com server):
```
listen_addresses: 194.xxx.xxx.xxx:1000
postgres:
  connection_string: postgresql://user:password@localhost:5432/immocarto?sslmode=require
  ssl_cert: '/etc/ssl/certs/ssl-cert-snakeoil.pem'
  ssl_key: '/etc/ssl/private/ssl-cert-snakeoil.key'
  ssl_root_cert: '/etc/letsencrypt/live/example.com/fullchain.pem'
  auto_publish: false
```

Thanks a lot
Sam
