### ISSUE TITLE
Table as a source produces 404 status on tiles on `0.14.2` when it was working on `0.13.0`

### ISSUE THREAD

**Issue by vfosnar** [maplibre/martin#1451]
```yaml
keep_alive: 75
listen_addresses: '0.0.0.0:80'
base_path: /tiles
worker_processes: 8
cache_size_mb: 512
preferred_encoding: gzip
web_ui: enable-for-all
postgres:
  connection_string: '...'
  default_srid: 4326
  pool_size: 20
  auto_bounds: skip
  tables:
    transportation_1:
      schema: public
      table: transportation_1
      srid: 3857
      geometry_column: geom
      id_column: ~
      minzoom: 0
      maxzoom: 19
      extent: 4096
      buffer: 64
      clip_geom: true
      geometry_type: GEOMETRY
      properties:
        type: string
```

## `/transportation_1`

```json
{
  "tilejson": "3.0.0",
  "tiles": [
    "http://localhost:8081/transportation_1/{z}/{x}/{y}"
  ],
  "vector_layers": [
    {
      "id": "transportation_1",
      "fields": {
        "tags": "json",
        "type": "string"
      }
    }
  ],
  "description": "public.transportation_1.geom",
  "maxzoom": 19,
  "minzoom": 0,
  "name": "transportation_1"
}
```

## `/transportation_1/5/16/10`
status code 404
