### ISSUE TITLE
Table sources, support WHERE conditions

### ISSUE THREAD

**Issue by artyomb** [maplibre/martin#1605]
That would be very useful to have "where" in table sources:

```yaml
  tables:
    tab_filtered:
      layer_id: table_source

      # Table name (required)
      table: table_source
      
      # SQL where conditions
      where: (TYPE = 'A') and (Pop > 100)
```

**Comment by artyomb** [comment]
Even better I guess:
```yaml
  tables:
    tab_filtered:
      layer_id: table_source
      table_sql: SELECT * FROM table WHERE ...
```
