### ISSUE TITLE
Docker build: TLS connection

### ISSUE THREAD

**Issue by saosebastiao** [maplibre/martin#209]
using the following docker-compose.yml

```
version: "3"

services:
  martin:
    image: urbica/martin
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - WATCH_MODE=true
      - DATABASE_URL=postgres://user:password@host:port/datanase
```

I get the following error:

```
martin_1  | [2021-05-03T16:21:31Z ERROR martin] Can't setup connection pool: Can't build connection pool: timed out waiting for connection: error performing TLS handshake: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915: (self signed certificate in certificate chain)
```

I have verified that I can manually connect to the database using psql. 

It looks like this could have been addressed in the past with this pull request: https://github.com/urbica/martin/pull/90

Has the official docker image been rebuilt since then? Is there any sort of logging I can help provide?
